### PR TITLE
Convert markdown issue templates into issue forms

### PR DESCRIPTION
**Pull request by webknjaz**
@pradyunsg and I asked GitHub to enable an alpha feature called Issue Forms for the whole @pypa org. And this PR introduces it to this repository.

Here's an example form in the pip repo: https://github.com/pypa/pip/issues/new?template=bug-report.yml.

The answers that users input are saved as normal markdown and the whole thing can be edited and updated upon creation.

Docs: https://gh-community.github.io/issue-template-feedback/structured/

### CODE REVIEW

**Comment by webknjaz** [comment]
@di ^

**Comment by di** [comment]
Is there any way to preview these?

**Comment by webknjaz** [comment]
No, only upon merge. But since I tested it in other repos, I'm quite sure that it is as close as possible to the original Markdown. If not, I'll send a follow up.

**Comment by webknjaz** [comment]
I thought I could preview it in the fork but forgot that it's under a feature flag.

**Review by di — APPROVED** [review]

**Comment by di** [comment]
We'll need to update some links over at https://github.com/pypa/warehouse as well.

**Comment by di** [comment]
Looks like some of these didn't make it: https://github.com/pypa/pypi-support/issues/new/choose

There's some formatting issues as well: https://github.com/pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME

**Comment by pradyunsg** [comment]
I'll file a follow up in a few minutes. :)

**Comment by webknjaz** [comment]
> Looks like some of these didn't make it: [pypa/pypi-support/issues/new/choose](https://github.com/pypa/pypi-support/issues/new/choose)

Oh, sorry about that! One is a YAML parsing error and another is caused by duplicate files like `IPv4`.

**Comment by webknjaz** [comment]
@di

> Looks like some of these didn't make it: [pypa/pypi-support/issues/new/choose](https://github.com/pypa/pypi-support/issues/new/choose)

This should be fixed by https://github.com/pypa/pypi-support/pull/927

> There's some formatting issues as well: [pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME](https://github.com/pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME)

I'm not sure what you mean by this. Are you referring to how I used bold and italics there?

**Comment by di** [comment]
> I'm not sure what you mean by this. Are you referring to how I used bold and italics there?

This part:

image

Looks like everything before the colon was supposed to be a label and not placeholder text, right?

**Comment by webknjaz** [comment]
> Looks like everything before the colon was supposed to be a label and not placeholder text, right?

No, that's what the original template had so I put it in the `value` field so that it's pre-filled. I wasn't sure about this but wanted to keep it as in the original templates for now. This could be discussed separately.

Also, you can clean up the default values by yourself, if you wish so — just drop those fields from YAML altogether.

**Comment by webknjaz** [comment]
> Looks like everything before the colon was supposed to be a label

Oh, and also things that you put in `label:` show up as titles in the resulting issue.

Look at this newly created issue https://github.com/pypa/pypi-support/issues/928 — this should give you some understanding of how it's saved. Or create some dummy issue from https://github.com/pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME as a test to see what happens.

**Pull request merged**
