### PR TITLE
Upgrade deprecated "about" to "description" @ forms

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by webknjaz** [comment]
@di you can see the warning box if you navigate to these yaml files pages on the main branch.

**Comment by lukehefson** [comment]
Hi @webknjaz   👋

Apologies for hijacking the comments here! But we've had [a recent change](https://github.com/gh-community/issue-forms-feedback/issues/91#issuecomment-823356578) which means that pypi-support will need to remove `title: ""`  entirely from any of your forms in order for them to work again! Sorry for the inconvenience!

**Comment by webknjaz** [comment]
@lukehefson I don't think we have empty-string titles tho

**Comment by webknjaz** [comment]
Oh, I see. One form does have this. Thanks!

**Pull request merged**
