### PR TITLE
Fix typos in the issue forms

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by webknjaz** [comment]
@di FYI there are red boxes on the pages of https://github.com/pypa/pypi-support/blob/main/.github/ISSUE_TEMPLATE/limit-request.yml and https://github.com/pypa/pypi-support/blob/main/.github/ISSUE_TEMPLATE/access-issues.yml that hint what the issue is.

**Comment by di** [comment]
> @di FYI there are red boxes on the pages of https://github.com/pypa/pypi-support/blob/main/.github/ISSUE_TEMPLATE/limit-request.yml and https://github.com/pypa/pypi-support/blob/main/.github/ISSUE_TEMPLATE/access-issues.yml that hint what the issue is.

Oh, that's really nice! I wish it did that for diffs in PRs as well 😉

**Comment by webknjaz** [comment]
@di AFAIK the warnings aren't visible in the PRs. It's an alpha feature after all. Do you want to get access to the feedback repo to share what your experience with GH? I think we could ask them to add you.

Also, let's merge this PR so the forms will reappear in the issue chooser.

**Comment by webknjaz** [comment]
Another follow-up: #931

**Comment by webknjaz** [comment]
> Do you want to get access to the feedback repo to share your experience with GH? I think we could ask them to add you.

@di FYI you and @ewdurbin should've received invitations to the feedback repo earlier today

**Pull request merged**
