### PR TITLE
Add an issue template chooser and pre-fill template titles

### PR DESCRIPTION
**Pull request by webknjaz**
Added:

* titles
* assignees
* template chooser config

(similar PR for Pip: https://github.com/pypa/pip/pull/7630/files; examples of how this looks: https://github.com/ansible/ansible/issues/new/choose, https://github.com/ansible/pylibssh/issues/new/choose, https://github.com/cherrypy/cheroot/issues/new/choose, https://github.com/sphinx-doc/sphinx/issues/new/choose)

### CODE REVIEW

**Comment by ewdurbin** [comment]
This is great, thank you @webknjaz. I think the only concern I have is the auto assignment. @di @yeraydiazdiaz, your thoughts?

**Comment by di** [comment]
Yeah, no auto-assignment please. These issues should be pick-up-able by any of the moderators.

**Comment by webknjaz** [comment]
Ah, I just looked into the old issues and noticed who picks up what issues. It may be a good idea to use a team for this but I haven't found any in the org teams directory...

**Comment by webknjaz** [comment]
FWIW I removed the assignments for now.

**Comment by ewdurbin** [comment]
Thank you @webknjaz

**Pull request merged**
